### PR TITLE
bowang-fixed footer overlay, modified new components (select, backdro…

### LINKED ISSUE #9: questions on new components
- backdrop purpose is unclear, let's add a quick explanation so people don't think it's a bug

select with error is a bit confusing, I'd expect to show an error when some input validation happens, is it possible to do that?

image

like I'd expect one of the arguments to be a function and then error the select if the validation function doesn't pass

also, there is some issue with the footer, it overlaps with the sidebar

image

### PR DESCRIPTION
**Pull request by bowang-ynd**
Fixed footer overlay, and modified select with error option for additional validation check on selected option, also added a short description on backdrop component

Closes #9

### CODE REVIEW

**Review by LatentDream — COMMENTED** [review]
✅ Tested the footer overlay
✅ Tested the Select error
✅ Backdrop description

___

Not in the original issue, but I found that:
- The backdrop has a spinner, but it focus on the Code bloc. That spinner is behind the code bloc on a normal screen, but if it's bigger, it's half in view / half hidden
image

**Comment by bowang-ynd** [comment]
@LatentDream Yes, I noticed this issue earlier. I will open a new issue to solve this. I think it is due to how the code snippet is formatted.

**Review by LatentDream — APPROVED** [review]
Okok, if the spinner is tackle in an other issue, this is ready to be merge

**Comment by edublancas** [comment]
@bowang-ynd don't forget to mark your PRs as ready for review, if they a draft, it's confusing whether we should review them or not

**Review by edublancas — APPROVED** [review]

**Pull request merged**
